package com.glancemap.glancemapwearos.presentation.navigation

object WatchRoutes {
    const val NAVIGATE = "navigate_screen"
    const val MAIN_MENU = "main_menu"
    const val POI = "poi_screen"
    const val GPX = "gpx_screen"
    const val MAPS = "maps_screen"
    const val DOWNLOAD = "download_screen"
    const val DOWNLOAD_SETTINGS = "download_settings_screen"
    const val SETTINGS = "settings_screen"
    const val USER_PROFILE_SETTINGS = "user_profile_settings_screen"
    const val COMPASS_SETTINGS = "compass_settings_screen"
    const val GPS_SETTINGS = "gps_settings_screen"
    const val GPS_ADVANCED_SETTINGS = "gps_advanced_settings_screen"
    const val RECORDING_SETTINGS = "recording_settings_screen"
    const val RECORDING_ADVANCED_SETTINGS = "recording_advanced_settings_screen"
    const val RECORDING_SOURCE_SETTINGS = "recording_source_settings_screen"
    const val RECORDING_BIKE_SENSOR_SETTINGS = "recording_bike_sensor_settings_screen"
    const val RECORDING_DASHBOARD_SETTINGS = "recording_dashboard_settings_screen"
    const val RECORDING_EXTERNAL_SENSORS = "recording_external_sensors_screen"
    const val TURN_BY_TURN_SETTINGS = "turn_by_turn_settings_screen"
    const val TURN_BY_TURN_ADVANCED_SETTINGS = "turn_by_turn_advanced_settings_screen"
    const val TURN_BY_TURN_GUIDANCE_SETTINGS = "turn_by_turn_guidance_settings_screen"
    const val TURN_BY_TURN_ALERTS_SETTINGS = "turn_by_turn_alerts_settings_screen"
    const val TURN_BY_TURN_FEEDBACK_SETTINGS = "turn_by_turn_feedback_settings_screen"
    const val TURN_BY_TURN_BACKGROUND_SETTINGS = "turn_by_turn_background_settings_screen"
    const val TURN_BY_TURN_DASHBOARD_SETTINGS = "turn_by_turn_dashboard_settings_screen"
    const val DEBUG_SETTINGS = "debug_settings_screen"
    const val GPX_SETTINGS = "gpx_settings_screen"
    const val GPX_APPEARANCE_SETTINGS = "gpx_appearance_settings_screen"
    const val GPX_TOOLS_SETTINGS = "gpx_tools_settings_screen"
    const val MAP_SETTINGS = "map_settings_screen"
    const val POI_SETTINGS = "poi_settings_screen"
    const val MAP_DISPLAY_SETTINGS = "map_display_settings_screen"
    const val MAP_ZOOM_SETTINGS = "map_zoom_settings_screen"
    const val THEME_SETTINGS = "theme_settings_screen"
    const val RESET_DEFAULTS_CONFIRM = "reset_defaults_confirm_screen"
    const val LICENSES = "licenses_screen"
}
